---
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  namespace: openshift-image-registry
  finalizers:
  - imageregistry.operator.openshift.io/finalizer
spec:
  managementState: Managed
  version: 3.10.0
  imagePullSpec: docker.io/openshift/origin-docker-registry:latest
  httpSecret: secret-enough-for-local-development
  storage:
    filesystem:
      volumeSource:
        emptyDir: {}
  replicas: 1
